<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerH8eq492\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerH8eq492/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerH8eq492.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerH8eq492\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerH8eq492\appProdProjectContainer([
    'container.build_hash' => 'H8eq492',
    'container.build_id' => '97820489',
    'container.build_time' => 1618514326,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerH8eq492');
